apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: SkyeBank
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/etaoko333/SkyeBank-Project.git'
    path: k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
