apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skyebank-app  # Changed to lowercase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/etaoko333/SkyeBank-Project.git  # Your GitHub repo
    targetRevision: main
    path: kubernetes  # Folder in your repo containing Kubernetes YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: skyebank
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
