apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyebank-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: skyebank  # Ensure this matches the pod template labels
  template:
    metadata:
      labels:
        app: skyebank  # Ensure this matches the selector
    spec:
      containers:
      - name: skyebank
        image: sholly333/skyebank:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: skyebank-service
spec:
  selector:
    app: skyebank  # Ensure this matches the pod labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
