apiVersion: apps/v1
kind: Deployment
metadata:
  name: skyebank-app
  namespace: skyebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skyebank
  template:
    metadata:
      labels:
        app: skyebank
    spec:
      containers:
        - name: skyebank
          image: sholly333/skyebank:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: skyebank-service
  namespace: skyebank
spec:
  selector:
    app: skyebank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
