name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Full history for accurate analysis
          clean: true  # Clean the working directory
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicit token if necessary

      # Run SonarQube analysis
      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Build Docker image and push to DockerHub
      - name: Docker Build and Push
        run: |
          docker build -t sholly333/skyebank:latest .
          docker push sholly333/skyebank:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      # Pull the Docker image
      - name: Docker Pull Image
        run: docker pull sholly333/skyebank:latest

      # Deploy the Docker container
      - name: Deploy to Container
        run: docker run -d --name skyebank-app -p 3000:80 sholly333/skyebank:latest

      # Deploy to Kubernetes
      - name: Update kubeconfig
        run: aws eks --region us-west-1 update-kubeconfig --name devopsola-cluster

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-service.yml
